---
title: "Murine Cerebellum scRNA-seq Analysis"
output: html_document
date: "2025-05-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("Seurat")
library("tidyverse")
library("Matrix")
library("stringr")
library("dplyr")
library("ggplot2")
library("reshape2")
library("purrr")
library("hdf5r")
library("remotes")
library("R.utils")
library("loupeR")
library("devtools")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
library("SeuratWrappers")
library("monocle3")
library("gtools")
library("scico")
library("Polychrome")
library("colorspace")
library("ComplexHeatmap")
library("clusterProfiler")
library("org.Mm.eg.db") 
library("dplyr")
library("stringr")
library("clusterProfiler")
library("igraph")

```


```{r, echo=TRUE, results='hide', message=FALSE}

# Preparing folder format for Seurat Object creation

raw_dir <- "GSE224466_RAW"
all_files <- list.files(raw_dir, full.names = TRUE, recursive = FALSE)

# Extract unique sample prefixes - only if data is retrieved directly from GEO

prefixes <- unique(gsub("_(barcodes|genes|matrix)\\.tsv$|_matrix\\.mtx$", "", basename(all_files)))


# Create sub-folders and move files - only if data is retrieved directly from GEO

for (prefix in prefixes) {
  sample_dir <- file.path(raw_dir, prefix)
  dir.create(sample_dir, showWarnings = FALSE)

  files_to_move <- list.files(
    raw_dir, 
    pattern = paste0("^", prefix, ".*\\.(tsv|mtx)$"), full.names = TRUE)
    
  file.rename(files_to_move,
            file.path(sample_dir, basename(files_to_move)))}
```



```{r }

# Reading each sample and creating a Seurat list with 24 objects

seurat_list <- lapply(all_files, function(dir) {
  sample_name <- basename(dir)
  data <- Read10X(data.dir = dir)
  seurat_obj <- CreateSeuratObject(counts = data, project = sample_name)
  seurat_obj$sample <- sample_name
  return(seurat_obj)})

# Exploring the data structure

seurat_list[[1]]@meta.data
```

```{r}
# Checking to see if the sample names were applied correctly 

lapply(seurat_list, function(x) x$sample[1])

# Total Cells

sum(sapply(seurat_list, ncol))

# Number of cells with 0 RNA counts for each sample before filtering 

sapply(seurat_list, function(seurat_obj) {sum(seurat_obj$nCount_RNA == 0, na.rm = TRUE)})


# Removing barcodes from the sample name for each cell

for (i in seq_along(seurat_list)) {
  seurat_list[[i]]$orig.ident <- sub("^[^ ]+\\s+", "", seurat_list[[i]]$orig.ident)
}

# Adding names to each Seurat object within list

names(seurat_list) <- sapply(seurat_list, function(obj) unique(obj$orig.ident))

for (i in seq_along(seurat_list)) {
  seurat_list[[i]]$sample <- names(seurat_list)[i]
}

# Sorting based on developmental stage

label_part <- sub(".*_(PAN[-_]CB[_-].*)", "\\1", names(seurat_list))

sorted_indices <- mixedorder(label_part)

seurat_list <- seurat_list[sorted_indices]

```

```{r}
# Identifying mitochondrial genes and creating a mitochondial percentage column for each cell

# Read in any of the genes files to determine comprehensive gene list 

genes_file <- "GSE224466_RAW/GSM7024833_PAN_CB_E13_A/genes.tsv"

genes_df <- read.table(genes_file, header = FALSE, col.names = c("ensembl_id", "gene_symbol"))
mito_genes_symbols <- grep("^mt-", genes_df$gene_symbol, value = TRUE, ignore.case = TRUE)
mito_ensembl_ids <- genes_df$ensembl_id[genes_df$gene_symbol %in% mito_genes_symbols]

print(mito_genes_symbols)

seurat_list <- lapply(seurat_list, function(seurat_obj) {
  seurat_obj[["percent.mt"]] <- PercentageFeatureSet(seurat_obj, features = mito_genes_symbols)
  return(seurat_obj)
})

head(seurat_list[[1]][["percent.mt"]])

# Identifying ribosomal genes and creating a ribosomal percentage column for each cell 

ribo_genes_symbols <- grep("^Rp[sl]", genes_df$gene_symbol, value = TRUE, ignore.case = TRUE)
ribo_genes_symbols <- ribo_genes_symbols[!grepl("ka|kc|-ps", ribo_genes_symbols)]
ribo_ensembl_ids <- genes_df$ensembl_id[genes_df$gene_symbol %in% ribo_genes_symbols]

print(ribo_genes_symbols)

seurat_list <- lapply(seurat_list, function(seurat_obj) {
  seurat_obj[["percent.ribo"]] <- PercentageFeatureSet(seurat_obj, features = ribo_genes_symbols)
  return(seurat_obj)
})

head(seurat_list[[1]][["percent.ribo"]])

```



``` {r}
# Sub-setting each object to filter out cells with over 10 % mitochondrial DNA, remove mitochondrial and ribosomal genes, cells with less than 3200 total transcripts and over 15,000 transcripts and those with less than 500 features 

filtered_list <- lapply(seurat_list, function (seurat_obj) {
  seurat_obj <- subset(seurat_obj, subset = percent.mt < 10)
  return (seurat_obj)
})

# Removing mitochondrial & ribosomal genes

genes_to_remove <- unique(c(mito_genes_symbols, ribo_genes_symbols))

filtered_list <- lapply(filtered_list, function(seurat_obj) {
  genes_keep <- setdiff(rownames(seurat_obj), genes_to_remove)
  subset(seurat_obj, features = genes_keep)
})


filtered_list <- lapply(filtered_list, function (seurat_obj) {
  seurat_obj <- subset(seurat_obj, subset =  nCount_RNA > 3200 & nCount_RNA < 15000 & nFeature_RNA > 500)
  return (seurat_obj)
})


# Removing genes with 0 counts across all cells 
  
filtered_list <- lapply(filtered_list, function(obj) {
  counts <- GetAssayData(obj, slot = "counts")
  genes_to_keep <- rowSums(counts) > 0
  subset(obj, features = names(genes_to_keep[genes_to_keep]))
})

# Summary statistics for each object 

lapply(filtered_list, function(seurat_obj) {summary(seurat_obj$nCount_RNA)})


# Count of cells after filtering

for (i in seq_along(filtered_list)) {cat("Sample", i, "has", ncol(filtered_list[[i]]), "cells after filtering\n")}

# Mean nCount_RNA after filtering

sapply(filtered_list, function(obj) {tapply(obj$nCount_RNA, obj$sample, mean)})

```


``` {r}
# Violin plot for % of mitochondrial genes in the first sample, checking to confirm that no cells have MT content above the threshold. 

VlnPlot(filtered_list[[1]], features = "percent.mt", pt.size = 0.1, layer = "counts") + NoLegend()

VlnPlot(filtered_list[[1]], features = "percent.ribo", pt.size = 0.1, layer = "counts") + NoLegend()

```



``` {r}
# Additional summary statistics

sapply(filtered_list, ncol)

sum(sapply(filtered_list, ncol))

sapply(filtered_list, function(seurat_obj) {sum(seurat_obj$nCount_RNA == 0, na.rm = TRUE)})

sapply(seurat_list, function(seurat_obj) {sum(seurat_obj$nCount_RNA > 2000 & seurat_obj$nCount_RNA < 15000, na.rm = TRUE)})

```



``` {r}
# Additional analysis (optional)

summary_df <- data.frame(
  Sample = names(filtered_list),
  Avg_nFeature_RNA = sapply(filtered_list, function(obj) mean(obj@meta.data$nFeature_RNA)),
  Avg_nCount_RNA = sapply(filtered_list, function(obj) mean(obj@meta.data$nCount_RNA))
)

print(summary_df)

melted_df <- melt(summary_df, id.vars = "Sample")

# Plot both metrics side-by-side
ggplot(melted_df, aes(x = Sample, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Sample", y = "Average", fill = "") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Average nFeature_RNA and nCount_RNA per Sample")


```





``` {r}
# Merging all objects into one Seurat object 

sample_names <- sapply(filtered_list, function(x) unique(x$sample))
names(filtered_list) <- sample_names

filtered_list <- lapply(names(filtered_list), function(name) {
  RenameCells(filtered_list[[name]], add.cell.id = name)
})
merged_obj <- purrr::reduce(filtered_list, merge)

# Maintaining only the developmental time period part of sample

merged_obj$clean_ident <- gsub("-", "_", merged_obj$orig.ident)

merged_obj$label_part <- sub(".*_(PAN_CB_[EP][0-9]+[A-Z]?)", "\\1", merged_obj$clean_ident)

merged_obj$label_part <- gsub("_(?=[A-Z]$)", "", merged_obj$label_part, perl = TRUE)


unique_labels <- unique(merged_obj$label_part)

ordered_labels <- c(
  "PAN_CB_E10C", "PAN_CB_E10D", "PAN_CB_E11A", "PAN_CB_E11B",
  "PAN_CB_E12A", "PAN_CB_E12B", "PAN_CB_E13A", "PAN_CB_E13B",
  "PAN_CB_E14A", "PAN_CB_E14B", "PAN_CB_E15A", "PAN_CB_E15B",
  "PAN_CB_E16C", "PAN_CB_E16D", "PAN_CB_E17A", "PAN_CB_E17B",
  "PAN_CB_P0A",  "PAN_CB_P0B",  "PAN_CB_P4A",  "PAN_CB_P4B",
  "PAN_CB_P7A",  "PAN_CB_P7B",  "PAN_CB_P10A", "PAN_CB_P10B"
)

merged_obj$label_part <- factor(merged_obj$label_part, levels = ordered_labels)


# Plotting Different Features

VlnPlot(merged_obj, features = "percent.mt", pt.size = 0.1, layer = "counts", group.by = "label_part") + NoLegend() + labs(x = "Sample", y = "Mitochondrial Gene %") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8), plot.title = element_blank()) 


VlnPlot(merged_obj, features = "nCount_RNA", pt.size = 0.1, layer = "counts", group.by = "label_part") + NoLegend() + labs(x = "Sample", y = "Total UMI Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8), plot.title = element_blank()) 


VlnPlot(merged_obj, features = "nFeature_RNA", pt.size = 0.1, layer = "counts", group.by = "label_part") + NoLegend() + labs(x = "Sample", y = "Feature Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8), plot.title = element_blank())

cor_val <- round(cor(merged_obj$nCount_RNA, merged_obj$nFeature_RNA), 2)

FeatureScatter(
  merged_obj,
  feature1 = "nCount_RNA",
  feature2 = "nFeature_RNA"
) +
  NoLegend() +
  ggtitle(NULL) +
  annotate("text", x = 8000, y = 3000, label = paste("r =", cor_val), size = 4)


df <- FetchData(merged_obj, vars = c("nCount_RNA", "label_part"))

# Compute mean per sample
means <- df %>%
  group_by(label_part) %>%
  summarize(mean_nCount = mean(nCount_RNA), .groups = "drop")

# Plot
ggplot(df, aes(x = label_part, y = nCount_RNA)) +
  geom_jitter(width = 0.2, size = 0.4, alpha = 0.6) +
  geom_point(data = means, aes(x = label_part, y = mean_nCount), 
             color = "darkred", size = 2.0) +
  labs(x = "Sample", y = "Total UMI Count") +
  scale_y_continuous(breaks = seq(0, max(df$nCount_RNA), by = 1500)) +  # Set y-axis breaks
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))

```


``` {r}
# Joining layers and normalizing the data  

merged_obj <- JoinLayers(merged_obj) # required for downstream processing

merged_obj <- NormalizeData(merged_obj, verbose = FALSE)
merged_obj <- FindVariableFeatures(merged_obj, selection.method = "vst", nfeatures = 2000, verbose = FALSE) # Based on the 2000 most variable features

dup_genes <- rownames(merged_obj[["RNA"]])[duplicated(rownames(merged_obj[["RNA"]]))]
merged_obj <- merged_obj[!rownames(merged_obj[["RNA"]]) %in% dup_genes, ]


# Regressing out cell cycle markers

s.genes <- tolower(cc.genes$s.genes)
g2m.genes <- tolower(cc.genes$g2m.genes)

valid_s_genes <- tolower(s.genes[s.genes %in% rownames(merged_obj)])
valid_g2m_genes <- tolower(g2m.genes[g2m.genes %in% rownames(merged_obj)])
 
# Temporary normalization (creates "data" layer)

merged_obj <- NormalizeData(merged_obj, assay = "RNA")

rownames(merged_obj) <- tolower(rownames(merged_obj))
 
# Score cell cycle phases

merged_obj <- CellCycleScoring(merged_obj, s.features = valid_s_genes, g2m.features = valid_g2m_genes, assay = "RNA", set.ident = TRUE)

# With cell cycle phase differences regressed out
merged_obj$CC.Difference <- merged_obj$S.Score - merged_obj$G2M.Score

merged_obj <- ScaleData(merged_obj, vars.to.regress = "CC.Difference", verbose = FALSE)

# Saving cell counts to a .csv

cell_counts <- as.data.frame(table(merged_obj$label_part))
colnames(cell_counts) <- c("Sample", "Number_of_Cells")

write.csv(cell_counts, "cell_counts.csv", row.names = FALSE)

``` 


``` {r}
# PCA, clustering and UMAP

merged_obj <- RunPCA(merged_obj, features = VariableFeatures(merged_obj), npcs = 40, verbose = FALSE)
merged_obj <- FindNeighbors(merged_obj, dims = 1:40, verbose = FALSE)
merged_obj <- FindClusters(merged_obj, resolution = 1.4, verbose = FALSE)  # Try different resolution from 0.4 - 1.4 ß
merged_obj <- RunUMAP(merged_obj, dims = 1:40, verbose = FALSE)

# Save to rds file so it can be loaded in directly if needed

saveRDS(merged_obj, file = "merged_obj.rds")
merged_obj <- readRDS("merged_obj.rds")


# Cluster summary

table(merged_obj$seurat_clusters)

```


``` {r}
# Checking # of PCAs to use for UMAP

ElbowPlot(merged_obj, ndims = 40)

#Visualization of UMAP

DimPlot(merged_obj, reduction = "umap", label = TRUE, group.by = "seurat_clusters") + NoLegend() + 
DimPlot(subset_obj, reduction = "umap", label = TRUE, group.by = "seurat_clusters") + NoLegend()
DimPlot(merged_obj, reduction = "umap", label = TRUE, repel = TRUE) +  NoLegend() + theme(plot.title = element_text(size = 4, face = "bold"))

# Sub-setting the data to include only cell types of cerebellar origin - skip this

excluded_clusters <- c("29", "36", "39", "40", "41", "30", "28", "37", "38")

Idents(merged_obj) <- "seurat_clusters"

subset_obj <- subset(merged_obj, idents = setdiff(levels(merged_obj), excluded_clusters))

``` 

```{r}
# Removing midbrain cells - optional (determine if these are present first)

midbrain_genes <- (c("tlx3", "isl1", "dlk1", "otx2", "sncg", "tal2", "phox2a", "phox2b"))

subset_obj <- NormalizeData(subset_obj, assay = "RNA")

subset_obj <- AddModuleScore(subset_obj, features = list(midbrain_genes), name = "MidbrainScore", assay = "RNA", slot = "data") # Seurat adds a "1" to the name when creating the column

# Determine the threshold for filtering midbrain genes

quantile(subset_obj$MidbrainScore1, probs = 0.95)
sum(seurat_final$MidbrainScore1 > 0.275)

# Visualize midbrain genes

FeaturePlot(subset_obj, features = "MidbrainScore1") + labs(title = "Midbrain Score")

# Subset the object based on desired threshold

subset_obj<- subset(subset_obj, subset = MidbrainScore1 <= 0.25)

VlnPlot(subset_obj, features = "MidbrainScore1", group.by = "seurat_clusters")


# Get the counts matrix
counts <- GetAssayData(rna_assay, slot = "counts")
# Remove duplicated genes
counts <- counts[!duplicated(rownames(counts)), ]
# Create a new RNA assay
new_rna <- CreateAssayObject(counts = counts)
# Replace the old RNA assay
seurat_final[["RNA"]] <- new_rna

# Re-clustering the data after removing midbrain cells and keeping only clusters of interest

seurat_final3 <- JoinLayers(seurat_final3)
seurat_final3 <- NormalizeData(subset_obj)
seurat_final3 <- FindVariableFeatures(seurat_final3, selection.method = "vst", nfeatures = 2000, verbose = FALSE) # Based on the 2000 most variable features

seurat_final3<- ScaleData(seurat_final3, vars.to.regress = "CC.Difference", verbose = FALSE)

seurat_final3 <- RunPCA(seurat_final3, features = VariableFeatures(seurat_final3), npcs = 40, verbose = FALSE)
seurat_final3 <- FindNeighbors(seurat_final3, dims = 1:40, verbose = FALSE)
seurat_final3 <- FindClusters(seurat_final3, resolution = 1.2, verbose = FALSE)

seurat_final3 <- RunUMAP(seurat_final3, dims = 1:40, verbose = FALSE)

DimPlot(seurat_final3, reduction = "umap", label = TRUE, group.by = "seurat_clusters") + NoLegend()

# Determining marker genes between each of the clusters, which are then used to assign cluster identity

all_markers <- FindAllMarkers(seurat_final3, assay ="RNA", slot = "data", only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

names(all_markers)

top_markers <- all_markers %>%
    group_by(cluster) %>%
    slice_max(order_by = avg_log2FC, n = 15) %>%
    ungroup()
 
# Save rds file of final data structure

saveRDS(seurat_final3, file = "seurat_final3.rds")
seurat_final3<- readRDS("seurat_final3.rds")

cluster_ids3 <- c(
  "0" = "GNPs/Granule Neurons", "1" = "GNPs/Granule Neurons", "2" = "Early Progenitors", "3" = "GABAergic Progenitors", "4" = "GNPs/Granule Neurons",
  "5" = "GABAergic Interneurons", "6" = "Early Progenitors" ,"7" = "GNPs/Granule Neurons",
  "8" = "Purkinje Neurons", "9" = "GNPs/Granule Neurons","10" = "GNPs/Granule Neurons",
  "11" = "GNPs/Granule Neurons", "12" = "Glutamatergic CNs", "13" = "Bergmann Glia", "14" = "GNPs/Granule Neurons","15" = "Bergmann Glia","16" = "Astrocytes",
  "17" = "GABAergic Interneurons", "18" = "Early Progenitors", "19" = "GNPs/Granule Neurons",
  "20" = "GNPs/Granule Neurons","21" = "GABAergic Progenitors","22" = "GABAergic Neuron Precursors",
  "23" = "GABAergic Progenitors", "24" = "RL Progenitors", "25" = "Roof Plate Cells", "26" = "VZ Progenitors",
  "27" = "GNPs/Granule Neurons","28" = "Glutamatergic CNs","29" = "Oligodendrocytes", "30" = "Purkinje Progenitors", "31" = "Glutamatergic CNs", "32" = "Purkinje Progenitors")


seurat_final3 <- RenameIdents(seurat_final3, cluster_ids3)

Idents(seurat_final3) <- "seurat_clusters"

n_clusters <- length(unique(Idents(seurat_final3)))

# Determining colour palette for visualizations

colors <- kelly.colors(n_clusters + 1)
filtered_cols <- colors[ colors != "#222222" ]
filtered_cols[ filtered_cols == "#f2f3f4" ] <- "#66CC99"
names(filtered_cols)[names(filtered_cols) == "white"] <- "green2"

desired_order <- c("red", "orange", "orangeyellow", "yellow", "yellowishpink", 
    "purplishpink", "purple", "violet", "blue", "lightblue", 
                   "green", "green2", "gray", "buff")
desired_order <- rev(desired_order)
filtered_cols <- filtered_cols[desired_order]

celltypes <- levels(Idents(seurat_final3))  # Or however you define your identities
named_colors <- setNames(filtered_cols[1:length(celltypes)], celltypes)
named_colors <- desaturate(named_colors, amount = 0.15)

DimPlot(seurat_final3, cols = named_colors, reduction = "umap", label = TRUE, repel = TRUE, label.size = 3.5, label.color = "black")  + labs(x= "UMAP-1 (1st Abstract Dimension of the UMAP Embedding)", y="UMAP-2 (2nd Abstract Dimension of the UMAP Embedding)",) + theme(plot.title = element_text(size = 2, face = "bold"), legend.position = "top", legend.justification = "center",
    legend.box.just = "center", legend.text = element_text(size = 7), legend.spacing.x = unit(0.025, "cm"), legend.key.size = unit(0.2, "lines"), axis.title = element_text(size = 9), axis.text = element_text(size = 8)) 

# Resetting to seurat cluster identities - optional 
Idents(seurat_final3) <- "seurat_clusters"

cluster_df <- data.frame(
  Barcode = colnames(seurat_final3),
  Cluster = as.character(Idents(seurat_final3))
)

# Saving cluster identities as a .csv file 
write.csv(cluster_df, "custom_clusters3.csv", row.names = FALSE)

```

``` {r}
#Cell type Proportion by Sample Date

seurat_final3$time_point <- sub(".*_(E[0-9]+|P[0-9]+)[A-Z]$", "\\1", seurat_final3$label_part)

table(seurat_final3$time_point) # There are some some samples E12, E14, that have very low cell counts

seurat_final3$CellType <- factor(Idents(seurat_final3), levels = levels(Idents(seurat_final3)))
celltypes <- levels(seurat_final3$CellType)



dftotal <- as.data.frame(table(Timepoint = seurat_final3$time_point, 
                            CellType = seurat_final3$CellType))

dftotal <- dftotal %>%
  group_by(Timepoint) %>%
  mutate(Percent = Freq / sum(Freq) * 100)


ggplot(dftotal, aes(x = Timepoint, y = Percent, fill = fct_rev(CellType))) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = named_colors) +
  labs(x = "Developmental Timepoint", y = "Cell Type Proportion (%)", fill = "Cell Type") +
  theme_minimal(base_size = 10) +
  theme(legend.position = "right",
        axis.text.x = element_text(angle = 45, hjust = 1, margin = margin(t = -15, r = 0, b = 5, l = 0)),
        axis.ticks.y = element_line(color = "black"),
        axis.ticks.length.y = unit(0.1, "cm"),
        axis.title.x = element_text(size = 30),  
        axis.title.y = element_text(size = 30)) + 
  scale_y_continuous(breaks = seq(0, 100, by = 10))

# Bubble plot based on proportions

ggplot(dftotal %>% filter(Percent > 0),  # Filter out zeros
       aes(x = Timepoint, y = CellType, size = Percent, fill = CellType)) +
  geom_point(shape = 21, stroke = 0) +  # stroke = 0 removes the outline
  scale_fill_manual(values = named_colors) +
  scale_size(range = c(1, 14)) +
  labs(
    x = "Developmental Timepoint", 
    y = "Cell Type", 
    size = "Proportion (%)", 
    fill = NULL
  ) +
  guides(
    fill = "none",  # Removes fill legend (Cell Type)
    size = guide_legend(override.aes = list(fill = "black"))  # All points in size legend are filled black
  ) +
  theme_minimal(base_size = 10) +
  theme(
        axis.text.x = element_text(angle = 45, hjust = 1, size = 10, face = "bold"),
        axis.text.y = element_text(size = 10, face = "bold"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        panel.grid.major = element_line(color = "grey90")
    )

# Plotting key genes on the UMAP

FeaturePlot(seurat_final3, features = c("ptf1a", "atoh1", "neurog2", "ascl1"))
 
```




```{r}
# Differential expression of the early neural progenitor clusters

target_clusters <- c("6", "2", "18") 

Early_NPCs <- subset(seurat_final3, idents = target_clusters)

Early_NPCs <- CellCycleScoring(Early_NPCs, s.features = s.genes, g2m.features = g2m.genes, assay = "RNA", set.ident = TRUE)

# With cell cycle phase differences regressed out
Early_NPCs$CC.Difference <- Early_NPCs$S.Score - Early_NPCs$G2M.Score

Idents(Early_NPCs) <- "seurat_clusters"

# Optional renaming

Early_NPCs <- RenameIdents(Early_NPCs, 
                           "18" = "EP #3", 
                           "2" = "EP #2", 
                           "6" = "EP #1")


Early_NPCs  <- NormalizeData(Early_NPCs)
Early_NPCs  <- FindVariableFeatures(Early_NPCs, selection.method = "vst", nfeatures = 2000, verbose = FALSE) # Based on the 2000 most variable features
#Early_NPCs<- ScaleData(Early_NPCs, vars.to.regress = "CC.Difference", verbose = FALSE, features = unique(npc_top_markers$gene))
Early_NPCs<- ScaleData(Early_NPCs, vars.to.regress = "CC.Difference", verbose = FALSE)

Early_NPCs <- RunPCA(Early_NPCs, features = VariableFeatures(Early_NPCs), npcs = 40, verbose = FALSE)
Early_NPCs <- FindNeighbors(Early_NPCs, dims = 1:20, verbose = FALSE)
Early_NPCs <- FindClusters(Early_NPCs, resolution = 0.3, verbose = FALSE)

Early_NPCs <- RunUMAP(Early_NPCs, dims = 1:20, verbose = FALSE)

DimPlot(Early_NPCs, reduction = "umap", label = TRUE, group.by = "seurat_clusters") + NoLegend()


NPC_Markers <- FindAllMarkers(Early_NPCs, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

npc_top_markers <- NPC_Markers %>%
    group_by(cluster) %>%
    slice_max(order_by = avg_log2FC, n = 20) %>%
    ungroup()

DoHeatmap(Early_NPCs, features = npc_top_markers$gene, size = 3, group.colors = c( "NA","NA","NA"), angle = 0) +
  theme(axis.text.y = element_text(size = 5),
        strip.text.x = element_text(angle = 0, hjust = 1.0, size = 8, margin = margin(t = 0.5)), legend.position ="right") + guides(color = guide_colorbar(), fill = guide_colorbar(), size = "none")


# Selecting only the clusters of interest from this cluster 

target_clusters <- c("0", "3", "2", "1") 

Early_NPCs2 <- subset(Early_NPCs, idents = target_clusters) 

Early_NPCs2 <- CellCycleScoring(Early_NPCs2, s.features = s.genes, g2m.features = g2m.genes, assay = "RNA", set.ident = TRUE)

 
# With cell cycle phase differences regressed out
Early_NPCs2$CC.Difference <- Early_NPCs2$S.Score - Early_NPCs2$G2M.Score

Early_NPCs2  <- NormalizeData(Early_NPCs2)
Early_NPCs2  <- FindVariableFeatures(Early_NPCs2, selection.method = "vst", nfeatures = 2000, verbose = FALSE) # Based on the 2000 most variable features

Early_NPCs2<- ScaleData(Early_NPCs2, vars.to.regress = "CC.Difference", verbose = FALSE) 

Idents(Early_NPCs2) <- "seurat_clusters"

# Optional renaming

Early_NPCs2 <- RenameIdents(Early_NPCs2, 
                           "1" = "Early NPC-1", 
                           "3" = "Early NPC-2", 
                           "2" = "Early NPC-3",
                           "4" = "Early NPC-4")
                           

NPC_Markers2 <- FindAllMarkers(Early_NPCs2, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

Early_NPCs2<- ScaleData(Early_NPCs2, vars.to.regress = "CC.Difference", verbose = FALSE,features = unique(NPC_Markers2$gene)) 

# Expression between cluster and rest of the cells

NPC_Markers2$pct.diff <- NPC_Markers2$pct.1 - NPC_Markers2$pct.2

# Exporting marker gene list to a .csv
write.csv(NPC_Markers2, "EarlyNPC_Marker_Genes.csv", row.names = FALSE)

# NPC_Markers2 <- NPC_Markers2[NPC_Markers2$"pct.diff" > 0.15,]

npc_top_markers2 <- NPC_Markers2 %>%
  group_by(cluster) %>%
  arrange(desc(avg_log2FC), desc(pct.diff)) %>%
  slice_head(n = 12) %>%
  arrange(cluster, desc(avg_log2FC)) %>%
  ungroup()

npc_top_markers2 <- npc_top_markers2[, 6:7]

# Heatmap visualization

DoHeatmap(Early_NPCs2, features = npc_top_markers2$gene, size = 3, draw.lines = TRUE, group.colors = c( "NA","NA","NA", "NA"), angle = 0, hjust = 0.5) + labs(y = "Gene Name") +
  theme(axis.text.y = element_text(size = 10),
        strip.text.x = element_text(angle = 0, hjust = 0.5, size = 8, margin = margin(t = 0.5),), legend.position ="right") + guides(color = guide_colorbar(), fill = guide_colorbar(), size = "none")

```

```{r}
# GO-Enrichment Analysis

NPC_Markers2$gene <- str_to_sentence(NPC_Markers2$gene)

# Running GO for per cluster 

go_results_list <- NPC_Markers2 %>%
  filter(p_val_adj < 0.05) %>%
  group_split(cluster) %>%
  setNames(paste0("Cluster_", unique(NPC_Markers2$cluster))) %>%
  lapply(function(df) {
    gene_df <- bitr(df$gene, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
    enrichGO(gene = gene_df$ENTREZID, OrgDb = org.Mm.eg.db, keyType = "ENTREZID",
             ont = "BP", pvalueCutoff = 0.05, readable = TRUE)
  })

go_df <- bind_rows(
  lapply(names(go_results_list), function(clust) {
    df <- as.data.frame(go_results_list[[clust]])
    df$Cluster <- clust
    return(df)
  })
)

write.csv(go_df, "GO_df.csv", row.names = FALSE)
go_df <- read_csv("GO_df.csv")



# Top 10 GO terms for each cluster: 

go_df_filtered <- go_df %>%
  filter(p.adjust < 0.01) %>%
  mutate(score = Count * FoldEnrichment) %>%
  group_by(Cluster) %>%
  arrange(desc(score)) %>%
  slice_head(n = 10) %>%
  ungroup()

go_df_filtered <- go_df_filtered %>%
  mutate(cluster_column = recode(Cluster,
                                 "Cluster_EP #4" = "Early NPC-4",
                                 "Cluster_EP #3" = "Early NPC-3",
                                 "Cluster_EP #2" = "Early NPC-2", 
                                 "Cluster_EP #1"= "Early NPC-1"
                                 # add more mappings as needed
                                 ))


go_df_filtered <- go_df_filtered %>%
  arrange(cluster_column, Description) %>%
  mutate(Description = factor(Description, levels = unique(Description)))

write.csv(go_df_filtered, "go_df_filtered.csv", row.names = FALSE)
go_df_filtered <- read_csv("go_df_filtered2.csv")

# Plotting GO terms per cluster

ggplot(go_df_filtered, aes(x = cluster_column, y = Description, size = Count, color = p.adjust)) +
  geom_point() +
  scale_color_continuous(low = "red", high = "blue", trans = "reverse") +
  theme_minimal(base_size = 10) +
  theme(axis.text.y = element_text(size = 6)) +
  labs(x = "Cluster", y = "GO Term", size = "Gene Count", color = "Adj. p-value")


```


```{r}
# Monocle3 Pseudotime Analysis, 

# First step is to turn the Seurat object into a to cell_data_set (cds)

cds2 <- as.cell_data_set(seurat_final3)

# Check partitions 

cds@clusters$UMAP$partitions

# Assigning all cells to one partition, only if you don't want Monocle to make its own

recreate.partition <- c(rep(1, length(cds2@colData@rownames)))
names(recreate.partition) <- cds2@colData@rownames
recreate.partition <- as.factor(recreate.partition)
cds2@clusters$UMAP$partitions <- recreate.partition

list_cluster<- seurat_final3@active.ident
cds2@clusters$UMAP$clusters <- list_cluster

# Transferring over embedding information and other relevant columns from the seurat obejct

reducedDims(cds2)$PCA <- seurat_final3@reductions$pca@cell.embeddings
reducedDims(cds2)$UMAP <- seurat_final3@reductions$umap@cell.embeddings
rowData(cds2)$gene_short_name <- rownames(rowData(cds2))
colData(cds2)$Sample_time <- seurat_final3@meta.data$time_point
colData(cds2)$seurat_clusters <- seurat_final3@meta.data$seurat_clusters


# Monocle clustering, only if using Monocle Partitions

# cds2 <- cluster_cells(cds2, reduction_method = "UMAP")


# Construct principal trajectory path
cds2 <- learn_graph(cds2) 

plot_cells(cds2, color_cells_by = "partition")

cds2 <- order_cells(cds2)

# Assign pseudotime values

colData(cds2)$pseudotime <- pseudotime(cds2)


# Order cells by cluster type

cds <- order_cells(cds, reduction_method = 'UMAP', root_cells = colnames(cds)[cds@clusters$UMAP$clusters == "Early Progenitors"])


saveRDS(cds2, file = "cds2.rds")
cds2 <- readRDS("cds2.rds")


# Various plots of the trajectory and pseudotime

plot_cells(cds, group_cells_by = "seurat_clusters", label_cell_groups = TRUE,
           label_groups_by_cluster = TRUE, reduction_method = "UMAP")

plot_cells(cds2, color_cells_by = "pseudotime")

plot_cells(cds2, color_cells_by = "pseudotime", label_leaves=FALSE,
label_branch_points=FALSE,
graph_label_size=3,
cell_size = 0.4, 
alpha = 0.3)


plot_cells(cds2, color_cells_by = "cluster", label_groups_by_cluster = FALSE, label_branch_points = FALSE, label_roots = TRUE, label_leaves = FALSE,  group_label_size = 4) + theme(legend.position = "right")


# Differential expression across branches, to identify key genes involved in branching cell fate

target_clusters <- c("3", "21", "13", "15")
cells_to_keep <- colData(cds2)$seurat_clusters %in% target_clusters
cds2_subset <- cds2[, cells_to_keep]

# Creating the model 
model_formula_str <- "~pseudotime * seurat_clusters"

# Fitting the model to the subset of data
gene_fits_subset <- fit_models(cds2_subset, model_formula_str = model_formula_str)

diff_expr_results_subset <- coefficient_table(gene_fits_subset)

# Filtering the result to only contain the genes the pass quality checks
sig_genes_interaction <- subset(diff_expr_results_subset,
                                 grepl("pseudotime:seurat_clusters", term) &
                                 q_value < 0.05 & num_cells_expressed > 10)

sig_genes_interaction <- sig_genes_interaction[order(sig_genes_interaction$q_value), ]


plotgenes <- head(sig_genes_interaction$gene_short_name, 20)
plotgenes <- data.frame(plotgenes)
colnames(plotgenes) <- "gene_name"

write.csv(plotgenes, file = "plotgenes.csv", row.names = FALSE)
read
plotgenes2 <- read.csv("plotgenes.csv", header = TRUE)



# Keeping genes of interest to visualzie expression over pseudotime

plotgenes <- c("id4", "pantr1", "sox4", "serpine2", "id3")

# plot_genes <- head(plotgenes$gene_name, 10)

cds2_subset.1 <- cds2_subset[rowData(cds2_subset)$gene_short_name %in% plotgenes,]

# Rename the clusters with cell type

colData(cds2_subset.1)$seurat_clusters <- factor(colData(cds2_subset.1)$seurat_clusters,
                                                 levels = c("3", "21","13", "15"), 
                                                 labels = c("GABAergic Progenitors", "GABAergic Progenitors", "Glial Lineage", "Glial Lineage"))


cds2_subset.1 <- order_cells(cds2_subset.1)

plot_genes_in_pseudotime(cds2_subset.1,
                         color_cells_by = "seurat_clusters",
                         min_expr = 0.5)
 
cds_gaba <- cds2_subset.1[, colData(cds2_subset.1)$seurat_clusters == "GABAergic Progenitors"]

cds_gaba <- choose_cells(cds_gaba)
cds_gaba <- order_cells(cds_gaba)
cds_gaba <- estimate_size_factors(cds_gaba)

cds_glial <- cds2_subset.1[, colData(cds2_subset.1)$seurat_clusters == "Glial Lineage"]

cds_glial <- choose_cells(cds_glial)
cds_glial <- order_cells(cds_glial)
cds_glial <- cds_glial[,Matrix::colSums(counts(cds_glial)) != 0]
cds_glial <- estimate_size_factors(cds_glial)

plot_genes_in_pseudotime(cds_gaba, color_cells_by = "seurat_clusters", min_expr = 0.5) + NoLegend()

gene_order <- c("id3", "id4", "pantr1", "serpine2", "sox4")

p <- plot_genes_in_pseudotime(cds_glial[gene_order,], color_cells_by = "seurat_clusters", min_expr = 0.5, label = FALSE) 

p + scale_color_manual(values = rep("turquoise", length(unique(colData(cds_glial)$seurat_clusters))))

plot_genes_in_pseudotime(cds2_subset.1,color_cells_by = "Sample_time", min_expr = 0.5)


cds2_subset <- estimate_size_factors(cds2_subset)
cds2_subset.1 <- estimate_size_factors(cds2_subset.1)


# Using graph_test() on subset of cells to determine modules of co-expressed genes

cds2_subset2 <- choose_cells(cds2)
cds2_subset2 <- order_cells(cds2_subset2)

subset_pr_test_res <- graph_test(cds2_subset2, neighbor_graph="principal_graph", cores=4)


subset_pr_test_rest2 <- row.names(subset(subset_pr_test_res, q_value < 0.05 & !is.na(q_value)))

cds2_subset2 <- preprocess_cds(cds2_subset2, num_dim = 50, method = "PCA")

gene_module_df <- find_gene_modules(cds2_subset2[subset_pr_test_rest2,], resolution=0.001)


write_csv(gene_module_df, file = "gene_module_df.csv")
gene_module_df <- read_csv("gene_module_df.csv")
write_csv(gene_module_df, file = "gene_module_df2.csv")


# Plotting modules on UMAP of subsetted data

selected_modules <- c(1, 2, 3, 4, 5, 6)
selected_modules <- c(2, 3, 5, 6, 7, 8)

gene_module_df <- gene_module_df %>% 
  filter(module %in% selected_modules)

plot_cells(
    cds2_subset2,
    genes = gene_module_df,
    show_trajectory_graph = FALSE,
    label_cell_groups = FALSE,
    label_leaves = FALSE,
    label_branch_points = FALSE,
    color_cells_by = "pseudotime"
)


top_genes_per_module <- gene_module_df %>%
  group_by(module) %>%
  group_split() %>%
  setNames(paste0("module_", sapply(., function(x) unique(x$module)))) %>%
  lapply(function(df) {
    genes <- df$id
    # Calculate variance for these genes
    gene_vars <- apply(exprs(cds2_subset2[genes, ]), 1, var)
    # Select top 5 by variance
    names(sort(gene_vars, decreasing = TRUE))[1:10]
  })

top_genes_df <- bind_rows(
  lapply(names(top_genes_per_module), function(mod) {
    data.frame(
      module = mod,
      gene = top_genes_per_module[[mod]],
      stringsAsFactors = FALSE
    )
  })
)
```


``` {r}
# Creating and saving Loupe objects for further analysis in Loupe Browser 10

seurat_final3 <- JoinLayers(seurat_final3)
create_loupe_from_seurat(seurat_final3, output_name = "loupe_5")

```


